# Generated by Django 3.2.6 on 2021-10-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_to_perform',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
