# Generated by Django 3.2.6 on 2021-10-23 03:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_alter_task_to_perform_complete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_to_Perform',
            new_name='TaskToPerform',
        ),
    ]
